# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Flux Resource Management Framework
tagline: A flexible framework for resource management customized for your HPC site
description: >- # this means to ignore newlines until "baseurl:"
  The Flux Resource Management Framework
baseurl: "https://hauten.github.io/flux-sandbox" # the subpath of your site, e.g. /blog
url: "https://hauten.github.io/flux-sandbox" # the base hostname & protocol for your site, e.g. http://example.com
image: /assets/images/logo-2x.png

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
repository: hauten/flux-sandbox
github: [metadata]

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock